### ISSUE TITLE
MSVC JIT compiler hangs if compilation fails

### ISSUE THREAD

**Issue by ncorgan** [pothosware/PothosCore#227]
In some circumstances (TBD), the batch script invoked by the module doesn't exit.

Ctrl+C leads to "Terminate batch job (Y/N)?", and even after entering Y, another Ctrl+C is necessary to exit.

**Comment by guruofquality** [comment]
If I modify the unit test "test_compiler" with an error, I dont see the terminate issue. What conditions were you running this in?

**Comment by ncorgan** [comment]
This came up in a linker error, but I'm not sure why that made a difference. Apply the attached patch and run `/util/tests/test_simd_dispatcher_utils_dump_header`. Running the generated batch script manually terminates as expected, but it hangs when run through the unit test.

[patch.txt](https://github.com/pothosware/PothosCore/files/6603107/patch.txt)

**Comment by guruofquality** [comment]
So from my observation, the hang is from the output pipe getting full since there is so much verbose output from cl.exe. Eventually the compiler hangs waiting for the output pipe to be drained. A quick hack to loop over the outPipe (inside an input pipe stream) and keep reading it until its closes lets the process finish.

So I think the fix is to read in a loop into a temporary buffer instead of waiting on the process -- or to redirect cl.exe output to a file which is read out instead for the error.

**Comment by guruofquality** [comment]
This branch compiler_support_read_pipe_fix should have the fix. I thought rather than merge it, we should just dogpile it on the other compiler related changes.
